In [21]:
print("Hello")

import numpy as np


Hello


In [22]:
lst = [1,2,3,4,5]
arr1 = np.array(lst)
arr2 = np.array([5,6,7,8,9])

In [23]:
print(arr1)
print(arr1+ arr2)

[1 2 3 4 5]
[ 6  8 10 12 14]


In [24]:
arr3 = [30, 40, 50]
arr4 = np.array([[1, 2, 3],
                 [4, 5 ,6]])

print(arr3+arr4)

print(arr3-arr4)

print(arr3*arr4)

print(arr3/arr4)

print(arr3//arr4)

print(arr3**arr4)

[[31 42 53]
 [34 45 56]]
[[29 38 47]
 [26 35 44]]
[[ 30  80 150]
 [120 200 300]]
[[30.         20.         16.66666667]
 [ 7.5         8.          8.33333333]]
[[30 20 16]
 [ 7  8  8]]
[[         30        1600      125000]
 [     810000   102400000 15625000000]]
